//WFP - Windows Functions Library
//Vlad Yanchuk 2019
//
#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define WFP_EVENT_NOEVENT 0
#define WFP_EVENT_CLOSE 1
#define WFP_EVENT_KEYDOWN 2
#define WFP_EVENT_KEYUP 3
#define WFP_EVENT_MOUSEDBLCLICK 4
#define WFP_EVENT_MOUSEDOWN 5
#define WFP_EVENT_MOUSEUP 6

#define WFP_EVENTPARAM_NOPARAM 0
#define WFP_EVENTPARAM_LEFT 1
#define WFP_EVENTPARAM_RIGHT 2

#define WFP_PIXBUFFSECTOR_SIZERGB 12288
#define WFP_PIXBUFFSECTOR_SIZEALPHA 4096
#define WFP_PIXBUFFSECTOR_SIZERGBA 16384

#endif // DEFINES_H_INCLUDED
